<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{753650ed-5d0e-43b3-92c0-79c094ab6917}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nVar1	: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nVar1 := nVar1 + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>